const express = require('express');
const sql = require('mssql/msnodesqlv8');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const util = require('util');
const execAsync = util.promisify(require('child_process').exec);

const app = express();
app.use(cors());
app.use(express.json());

const config = { connectionString: 'Driver={ODBC Driver 17 for SQL Server};Server=localhost;Database=dbDrawingManagment;Trusted_Connection=Yes;TrustServerCertificate=Yes;', connectionTimeout: 15000, requestTimeout: 30000, pool: { max: 30, min: 2, idleTimeoutMillis: 30000 } };
const ALLOWED_SRSC_FOLDERS = ['SLD','DOC','PIC','Catalog'];
const IMAGE_EXTENSIONS = new Set(['.jpg','.jpeg','.png','.gif','.bmp','.webp','.svg','.tif','.tiff','.ico']);
const INLINE_EXTENSIONS = new Set(['.pdf',...IMAGE_EXTENSIONS]);
let srscStatusCache = null, srscStatusComputing = null, pdfCache = null, pdfCacheComputing = null;

function normalizeRelativePath(value){if(value===null||value===undefined)return null;const n=String(value).trim().replace(/\\/g,'/');if(!n||n.startsWith('/')||/^[A-Za-z]:\//.test(n))return null;const p=n.split('/').filter(Boolean);if(p.includes('..'))return null;return p.join(path.sep);}
function getSafeNodeRoot(rootPath,folderPath){const r=normalizeRelativePath(folderPath);return rootPath&&r?path.resolve(String(rootPath),r):null;}
function isPathInside(parent,child){const r=path.relative(path.resolve(parent),path.resolve(child));return r===''||!!r&&r!=='..'&&!r.startsWith('..'+path.sep)&&!path.isAbsolute(r);}
function getCanonicalAllowedFolder(name){return ALLOWED_SRSC_FOLDERS.find(x=>x.toLowerCase()===String(name).toLowerCase())||null;}
function isSafeChildPath(base,rel){if(rel===null||rel===undefined)return null;const n=String(rel).replace(/\\/g,'/'),p=n.split('/').filter(Boolean);if(!p.length||p.includes('..')||n.startsWith('/')||/^[A-Za-z]:\//.test(n))return null;const full=path.resolve(base,...p);return isPathInside(base,full)?full:null;}
function getFileKind(name){const e=path.extname(name).toLowerCase();if(e==='.pdf')return'pdf';if(IMAGE_EXTENSIONS.has(e))return'image';if(['.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt','.rtf'].includes(e))return'document';if(['.dwg','.dxf','.dws','.dwt','.sldprt','.sldasm','.slddrw','.step','.stp','.iges','.igs'].includes(e))return'cad';return'file';}

async function testDatabaseConnection(){try{const pool=await sql.connect(config);console.log('Database: dbDrawingManagment');console.log('SQL Server connected successfully');try{await pool.request().query(`IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_DanieliPDF_NodeID' AND object_id=OBJECT_ID('dbo.DanieliPDF')) CREATE INDEX IX_DanieliPDF_NodeID ON dbo.DanieliPDF(NodeID,PDFID);`);console.log('PDF lookup index verified');}catch(e){console.warn('PDF index check skipped:',e.message);}warmPdfCache();}catch(e){console.error('SQL Server connection failed');console.error(e);}}
async function warmPdfCache(){if(pdfCache||pdfCacheComputing)return pdfCacheComputing;pdfCacheComputing=sql.query(`SELECT PDFID,NodeID,NodeCode,PDFName FROM dbo.DanieliPDF ORDER BY NodeID,PDFID`).then(r=>{pdfCache=r.recordset||[];pdfCacheComputing=null;console.log(`PDF cache ready: ${pdfCache.length.toLocaleString()} records`);return pdfCache;}).catch(e=>{pdfCacheComputing=null;console.error('PDF cache warm-up failed:',e.message);return[];});return pdfCacheComputing;}

app.get('/api/nodes',async(req,res)=>{try{const r=await sql.query(`SELECT NodeID,ParentID,NodeCode,NodeName,IsActive FROM dbo.Nodes ORDER BY NodeID`);res.json(r.recordset);}catch(e){console.error('Nodes query failed:',e);res.status(500).json({error:e.message});}});

app.post('/api/nodes',async(req,res)=>{const nodeCode=typeof req.body?.NodeCode==='string'?req.body.NodeCode.trim():'';const nodeName=typeof req.body?.NodeName==='string'?req.body.NodeName.trim():'';const parentId=Number(req.body?.ParentID);if(!nodeCode)return res.status(400).json({error:'Node Code is required.'});if(!nodeName)return res.status(400).json({error:'Node Name is required.'});if(!Number.isInteger(parentId)||parentId<=0)return res.status(400).json({error:'A valid parent Node is required.'});try{const pool=await sql.connect(config),tx=new sql.Transaction(pool);await tx.begin(sql.ISOLATION_LEVEL.SERIALIZABLE);try{const q=new sql.Request(tx);q.input('parentId',sql.Int,parentId);q.input('nodeCode',sql.NVarChar(100),nodeCode);q.input('nodeName',sql.NVarChar(255),nodeName);const pr=await q.query(`SELECT TOP 1 NodeID,FolderPath,PathID FROM dbo.Nodes WITH(UPDLOCK,HOLDLOCK) WHERE NodeID=@parentId`);if(!pr.recordset.length){await tx.rollback();return res.status(404).json({error:'Parent Node not found.'});}const parent=pr.recordset[0],safe=v=>String(v).replace(/[\\/:*?"<>|]/g,'-').trim(),pf=parent.FolderPath?String(parent.FolderPath).trim():'',fp=pf?`${pf}\\${safe(nodeCode)} -${safe(nodeName)}`:`${safe(nodeCode)} -${safe(nodeName)}`;const ir=await new sql.Request(tx).query(`SELECT COLUMNPROPERTY(OBJECT_ID('dbo.Nodes'),'NodeID','IsIdentity') AS IsIdentity`);let ins;if(Number(ir.recordset[0]?.IsIdentity)===1){const r=new sql.Request(tx);r.input('parentId',sql.Int,parentId);r.input('nodeCode',sql.NVarChar(100),nodeCode);r.input('nodeName',sql.NVarChar(255),nodeName);r.input('folderPath',sql.NVarChar(sql.MAX),fp);r.input('pathId',sql.Int,parent.PathID??null);ins=await r.query(`INSERT INTO dbo.Nodes(ParentID,NodeCode,NodeName,IsActive,CreatedAt,UpdatedAt,FolderPath,PathID) OUTPUT INSERTED.* VALUES(@parentId,@nodeCode,@nodeName,1,SYSUTCDATETIME(),SYSUTCDATETIME(),@folderPath,@pathId)`);}else{const idr=await new sql.Request(tx).query(`SELECT ISNULL(MAX(NodeID),0)+1 AS NewNodeID FROM dbo.Nodes WITH(UPDLOCK,HOLDLOCK)`),id=Number(idr.recordset[0].NewNodeID),r=new sql.Request(tx);r.input('nodeId',sql.Int,id);r.input('parentId',sql.Int,parentId);r.input('nodeCode',sql.NVarChar(100),nodeCode);r.input('nodeName',sql.NVarChar(255),nodeName);r.input('folderPath',sql.NVarChar(sql.MAX),fp);r.input('pathId',sql.Int,parent.PathID??null);ins=await r.query(`INSERT INTO dbo.Nodes(NodeID,ParentID,NodeCode,NodeName,IsActive,CreatedAt,UpdatedAt,FolderPath,PathID) OUTPUT INSERTED.* VALUES(@nodeId,@parentId,@nodeCode,@nodeName,1,SYSUTCDATETIME(),SYSUTCDATETIME(),@folderPath,@pathId)`);}await tx.commit();srscStatusCache=null;res.status(201).json({success:true,node:ins.recordset[0]});}catch(e){try{await tx.rollback();}catch(_){}throw e;}}catch(e){console.error('Node creation failed:',e);res.status(500).json({error:e.message});}});

app.delete('/api/nodes/:nodeId',async(req,res)=>{const nodeId=Number(req.params.nodeId);if(!Number.isInteger(nodeId)||nodeId<=0)return res.status(400).json({error:'Invalid Node ID.'});try{const p=await sql.connect(config),q=p.request();q.input('nodeId',sql.Int,nodeId);const n=await q.query(`SELECT TOP 1 NodeID FROM dbo.Nodes WHERE NodeID=@nodeId`);if(!n.recordset.length)return res.status(404).json({error:'Node not found.'});if((await q.query(`SELECT TOP 1 NodeID FROM dbo.Nodes WHERE ParentID=@nodeId`)).recordset.length)return res.status(409).json({error:'This Node has child Nodes. Delete or move the child Nodes first.'});if((await q.query(`SELECT TOP 1 PDFID FROM dbo.DanieliPDF WHERE NodeID=@nodeId`)).recordset.length)return res.status(409).json({error:'This Node has registered PDF files. Remove the PDF records first.'});await q.query(`DELETE FROM dbo.Nodes WHERE NodeID=@nodeId`);srscStatusCache=null;res.json({success:true,deleted:true,nodeId});}catch(e){console.error('Node deletion failed:',e);if(e.number===547)return res.status(409).json({error:'This Node is referenced by another database record and cannot be deleted.'});res.status(500).json({error:e.message});}});

app.get('/api/pdfs',async(req,res)=>{try{const id=req.query.nodeId!==undefined?Number(req.query.nodeId):null;if(id!==null&&(!Number.isInteger(id)||id<=0))return res.status(400).json({error:'Invalid Node ID'});const data=pdfCache||await warmPdfCache();res.json(id===null?data:data.filter(x=>Number(x.NodeID)===id));}catch(e){console.error('PDF query failed:',e);res.status(500).json({error:e.message});}});

async function computeSrscStatus(){const r=await sql.query(`SELECT N.NodeID,N.FolderPath,N.PathID,P.RootPath FROM dbo.Nodes N LEFT JOIN dbo.tblPath P ON N.PathID=P.PathID WHERE N.FolderPath IS NOT NULL AND LTRIM(RTRIM(N.FolderPath))<>''`),ids=[];for(const x of r.recordset){const root=getSafeNodeRoot(x.RootPath,x.FolderPath);if(!root)continue;try{if(!fs.existsSync(root)||!fs.statSync(root).isDirectory())continue;if(ALLOWED_SRSC_FOLDERS.some(n=>{try{const p=path.join(root,n);return fs.existsSync(p)&&fs.statSync(p).isDirectory();}catch(_){return false;}}))ids.push(x.NodeID);}catch(_){} }return ids;}
async function getSrscStatus(force=false){if(!force&&srscStatusCache)return srscStatusCache;if(srscStatusComputing)return srscStatusComputing;srscStatusComputing=computeSrscStatus().then(ids=>{srscStatusCache=ids;srscStatusComputing=null;return ids;}).catch(e=>{srscStatusComputing=null;throw e;});return srscStatusComputing;}
app.get('/api/srsc-status',async(req,res)=>{try{if(req.query.refresh!=='1'&&!srscStatusCache){getSrscStatus(false).catch(e=>console.error('SRSC background scan failed:',e.message));return res.json({nodeIds:[],count:0,pending:true});}const ids=await getSrscStatus(req.query.refresh==='1');res.json({nodeIds:ids,count:ids.length,pending:false});}catch(e){res.status(500).json({error:e.message});}});

async function getNodeStorage(id){const q=new sql.Request();q.input('nodeId',sql.Int,id);const r=await q.query(`SELECT TOP 1 N.NodeID,N.NodeCode,N.FolderPath,N.PathID,P.RootPath FROM dbo.Nodes N LEFT JOIN dbo.tblPath P ON N.PathID=P.PathID WHERE N.NodeID=@nodeId`);return r.recordset[0]||null;}
app.get('/api/node-folders/:nodeId',async(req,res)=>{const id=Number(req.params.nodeId);if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:'Invalid Node ID'});try{const n=await getNodeStorage(id);if(!n)return res.status(404).json({error:'Node not found'});const root=getSafeNodeRoot(n.RootPath,n.FolderPath);if(!root)return res.json({nodeId:id,nodeCode:n.NodeCode,hasFolderPath:false,folders:[]});if(!fs.existsSync(root)||!fs.statSync(root).isDirectory())return res.json({nodeId:id,nodeCode:n.NodeCode,hasFolderPath:true,folderExists:false,folders:[]});const folders=ALLOWED_SRSC_FOLDERS.map(name=>{const p=path.join(root,name);try{return{name,exists:fs.existsSync(p)&&fs.statSync(p).isDirectory()};}catch(_){return{name,exists:false};}}).filter(x=>x.exists);res.json({nodeId:id,nodeCode:n.NodeCode,hasFolderPath:true,folderExists:true,folders});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/node-folder-files/:nodeId/:folderName',async(req,res)=>{const id=Number(req.params.nodeId),folder=getCanonicalAllowedFolder(req.params.folderName),sub=typeof req.query.subPath==='string'?req.query.subPath:'';if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:'Invalid Node ID'});if(!folder)return res.status(400).json({error:'Folder is not allowed'});try{const n=await getNodeStorage(id);if(!n)return res.status(404).json({error:'Node not found'});const root=getSafeNodeRoot(n.RootPath,n.FolderPath),target=root&&path.join(root,folder);if(!root||!isPathInside(root,target)||!fs.existsSync(target)||!fs.statSync(target).isDirectory())return res.status(404).json({error:'SRSC folder not found'});let browse=target;if(sub){const r=isSafeChildPath(target,sub);if(!r||!fs.existsSync(r)||!fs.statSync(r).isDirectory())return res.status(404).json({error:'Subfolder not found'});browse=r;}const items=[];for(const e of fs.readdirSync(browse,{withFileTypes:true})){if(e.name.startsWith('~$'))continue;const p=path.join(browse,e.name);try{const st=fs.statSync(p);if(e.isDirectory())items.push({name:e.name,type:'folder',kind:'folder'});else if(e.isFile())items.push({name:e.name,type:'file',kind:getFileKind(e.name),extension:path.extname(e.name).toLowerCase(),size:st.size,modifiedAt:st.mtime.toISOString()});}catch(_){}}items.sort((a,b)=>a.type!==b.type?(a.type==='folder'?-1:1):a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));res.json({nodeId:id,nodeCode:n.NodeCode,folder,subPath:sub,items});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/node-file',async(req,res)=>{const id=Number(req.query.nodeId),folder=getCanonicalAllowedFolder(req.query.folder),file=req.query.file;if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:'Invalid Node ID'});if(!folder||!file||typeof file!=='string')return res.status(400).json({error:'Invalid folder or file'});try{const n=await getNodeStorage(id);if(!n)return res.status(404).json({error:'Node not found'});const root=getSafeNodeRoot(n.RootPath,n.FolderPath),base=root&&path.join(root,folder),full=base&&isSafeChildPath(base,file);if(!full||!fs.existsSync(full)||!fs.statSync(full).isFile())return res.status(404).json({error:'File not found'});const ext=path.extname(full).toLowerCase();res.setHeader('Content-Disposition',`${INLINE_EXTENSIONS.has(ext)?'inline':'attachment'}; filename="${path.basename(full).replace(/"/g,'')}"`);res.sendFile(full);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/pdf-open/:pdfId',async(req,res)=>{const id=Number(req.params.pdfId);if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:'Invalid PDF ID'});try{const q=new sql.Request();q.input('pdfId',sql.Int,id);const r=await q.query(`SELECT d.PDFName,p.RootPath FROM dbo.DanieliPDF d JOIN dbo.tblPath p ON d.PathID=p.PathID WHERE d.PDFID=@pdfId`);if(!r.recordset.length)return res.status(404).json({error:'PDF record not found'});const full=path.join(r.recordset[0].RootPath,r.recordset[0].PDFName);if(!fs.existsSync(full))return res.status(404).json({error:'PDF file not found on disk'});await execAsync(`start "" "${full}"`);res.json({success:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/pdf-file/:pdfId',async(req,res)=>{const id=Number(req.params.pdfId);if(!Number.isInteger(id)||id<=0)return res.status(400).json({error:'Invalid PDF ID'});try{const q=new sql.Request();q.input('pdfId',sql.Int,id);const r=await q.query(`SELECT d.PDFName,p.RootPath FROM dbo.DanieliPDF d JOIN dbo.tblPath p ON d.PathID=p.PathID WHERE d.PDFID=@pdfId`);if(!r.recordset.length)return res.status(404).json({error:'PDF record not found'});const full=path.join(r.recordset[0].RootPath,r.recordset[0].PDFName);if(!fs.existsSync(full))return res.status(404).json({error:'PDF file not found on disk'});res.sendFile(full);}catch(e){res.status(500).json({error:e.message});}});
app.listen(3000,'0.0.0.0',async()=>{console.log('Server running on http://0.0.0.0:3000');await testDatabaseConnection();});
