(() => {
'use strict';
const state={tables:[],meta:null,table:null,rows:[],page:1,pageSize:50,total:0,search:'',sortBy:'',sortDir:'asc',editing:null};
const API_BASE=(window.DMS_API_BASE||(location.port==='5500'||location.port==='5501'?location.protocol+'//'+location.hostname+':3000':''));
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,options={}){const r=await fetch(API_BASE+url,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d;}
function notice(msg){$('notice').textContent=msg;$('notice').classList.toggle('hidden',!msg);}
async function boot(){try{const me=await api('/api/auth/me');if(!me.authenticated||!me.user?.isAdmin){location.href='/index.html';return;}$('adminIdentity').textContent='Admin · '+(me.user.username||'');const d=await api('/api/admin/tables');state.tables=d.tables||[];$('tableCount').textContent=state.tables.length;renderTables();}catch(e){notice(e.message);}}
function renderTables(){const q=$('tableSearch').value.trim().toLowerCase();const list=state.tables.filter(t=>t.tableName.toLowerCase().includes(q));$('tableList').innerHTML=list.map(t=>'<button class="table-entry '+(t.tableName===state.table?'active':'')+'" data-table="'+esc(t.tableName)+'"><span>'+esc(t.tableName)+'</span><small>'+Number(t.approxRows||0).toLocaleString()+'</small></button>').join('')||'<div class="mgmt-loading">No tables found.</div>';document.querySelectorAll('.table-entry').forEach(b=>b.onclick=()=>selectTable(b.dataset.table));}
async function selectTable(name){state.table=name;state.page=1;state.search='';state.sortBy='';state.sortDir='asc';$('rowSearch').value='';renderTables();await loadRows();}
async function loadRows(){try{notice('');const d=await api('/api/admin/tables/'+encodeURIComponent(state.table)+'/rows?page='+state.page+'&pageSize='+state.pageSize+'&search='+encodeURIComponent(state.search)+'&sortBy='+encodeURIComponent(state.sortBy)+'&sortDir='+encodeURIComponent(state.sortDir));state.meta=d.table;state.rows=d.rows;state.total=d.total;state.page=d.page;renderGrid();updatePager();$('addRowBtn').disabled=state.meta.readOnly; $('tableTitle').textContent=state.table;$('tableMeta').textContent=state.total.toLocaleString()+' records · '+(state.meta.readOnly?'Read only':'Editable');}catch(e){notice(e.message);}}
function sortByColumn(column){if(state.sortBy===column){state.sortDir=state.sortDir==='asc'?'desc':'asc';}else{state.sortBy=column;state.sortDir='asc';}state.page=1;loadRows();}
function updatePager(){const pages=Math.max(1,Math.ceil(state.total/state.pageSize));$('pageInfo').textContent='Page '+state.page+' / '+pages;$('prevBtn').disabled=state.page<=1;$('nextBtn').disabled=state.page>=pages;}
function display(v){if(v===null||v===undefined)return '<span style="opacity:.45">NULL</span>';if(typeof v==='boolean')return v?'✓':'—';return esc(v);}
function renderGrid(){const cols=state.meta.columns;const head=cols.map(c=>{const active=state.sortBy===c.ColumnName;const arrow=active?(state.sortDir==='asc'?' ▲':' ▼'):'';return '<th><button type="button" class="column-sort" data-column="'+esc(c.ColumnName)+'" title="Sort by '+esc(c.ColumnName)+'">'+esc(c.ColumnName)+(c.IsPrimaryKey?' · PK':'')+arrow+'</button></th>';}).join('')+'<th>Actions</th>';$('dataGrid').querySelector('thead').innerHTML='<tr>'+head+'</tr>';document.querySelectorAll('.column-sort').forEach(b=>b.onclick=()=>sortByColumn(b.dataset.column));const body=$('dataGrid').querySelector('tbody');if(!state.rows.length){body.innerHTML='<tr><td class="mgmt-empty" colspan="'+(cols.length+1)+'">No records.</td></tr>';return;}body.innerHTML=state.rows.map((row,i)=>'<tr>'+cols.map(c=>'<td class="'+(c.IsPrimaryKey?'pk-cell':'')+'">'+display(row[c.ColumnName])+'</td>').join('')+'<td><div class="row-actions"><button class="row-btn edit-row" data-i="'+i+'">Edit</button><button class="row-btn delete delete-row" data-i="'+i+'">Delete</button></div></td></tr>').join('');document.querySelectorAll('.edit-row').forEach(b=>b.onclick=()=>openEdit(state.rows[Number(b.dataset.i)]));document.querySelectorAll('.delete-row').forEach(b=>b.onclick=()=>deleteRow(state.rows[Number(b.dataset.i)]));}
function inputFor(c,value,mode){const ro=c.IsIdentity||c.IsComputed||c.IsPrimaryKey||c.ReadOnly;const fk=state.meta.foreignKeys.find(x=>x.ColumnName===c.ColumnName);const type=String(c.DataType).toLowerCase();let control='';if(type==='bit'){control='<div class="boolean-field"><input id="fld_'+esc(c.ColumnName)+'" type="checkbox" '+(value?'checked':'')+(ro?' disabled':'')+'></div>';}else if(type.includes('text')||type==='ntext'){control='<textarea id="fld_'+esc(c.ColumnName)+'" '+(ro?'disabled':'')+'>'+esc(value??'')+'</textarea>';}else{control='<input id="fld_'+esc(c.ColumnName)+'" '+(ro?'disabled':'')+' value="'+esc(value??'')+'" '+(c.IsNullable?'':'required')+'>';}return '<div class="form-field"><label>'+esc(c.ColumnName)+(c.IsPrimaryKey?' <span class="readonly-tag">PK</span>':'')+(c.IsIdentity?' <span class="readonly-tag">IDENTITY</span>':'')+'</label>'+control+'</div>';}
function openModal(mode,row){state.editing=mode==='edit'?row:null;$('modalTitle').textContent=mode==='edit'?'Edit Record':'Add Record';$('modalSubtitle').textContent=state.table;$('formError').classList.add('hidden');let fields=state.meta.columns.filter(c=>!(c.ColumnName==='PasswordHash'));fields.forEach(c=>{fields});$('formFields').innerHTML=fields.map(c=>inputFor(c,row?.[c.ColumnName],mode)).join('')+(state.table==='Users'?'<div class="form-field full"><label>New Password '+(mode==='edit'?'(optional)':'*')+'</label><input id="fld_password" type="password" minlength="8" '+(mode==='edit'?'':'required')+' autocomplete="new-password"></div>':'');$('recordModal').classList.remove('hidden');}
function openEdit(row){openModal('edit',row);}
function keysFor(row){const out={};state.meta.columns.filter(c=>c.IsPrimaryKey).forEach(c=>out[c.ColumnName]=row[c.ColumnName]);return out;}
function collect(){const data={};for(const c of state.meta.columns){if(c.IsIdentity||c.IsComputed||c.IsPrimaryKey||c.ReadOnly||c.ColumnName==='PasswordHash')continue;const el=$('fld_'+c.ColumnName);if(!el)continue;data[c.ColumnName]=c.DataType.toLowerCase()==='bit'?el.checked:el.value;}return data;}
async function save(e){e.preventDefault();try{$('modalSave').disabled=true;const data=collect();const password=$('fld_password')?.value||'';const body={data};if(password)body.password=password;if(state.editing)body.keys=keysFor(state.editing);const method=state.editing?'PATCH':'POST';await api('/api/admin/tables/'+encodeURIComponent(state.table)+'/rows',{method,body:JSON.stringify(body)});$('recordModal').classList.add('hidden');await loadRows();}catch(err){$('formError').textContent=err.message;$('formError').classList.remove('hidden');}finally{$('modalSave').disabled=false;}}
async function deleteRow(row){if(!confirm('Delete this record from '+state.table+'? This cannot be undone.'))return;try{await api('/api/admin/tables/'+encodeURIComponent(state.table)+'/rows',{method:'DELETE',body:JSON.stringify({keys:keysFor(row)})});await loadRows();}catch(e){notice(e.message);}}
$('tableSearch').oninput=renderTables;$('rowSearch').oninput=()=>{clearTimeout(window.__mgmtSearch);window.__mgmtSearch=setTimeout(()=>{state.search=$('rowSearch').value.trim();state.page=1;loadRows();},300)};$('refreshBtn').onclick=loadRows;$('prevBtn').onclick=()=>{if(state.page>1){state.page--;loadRows();}};$('nextBtn').onclick=()=>{if(state.page<Math.ceil(state.total/state.pageSize)){state.page++;loadRows();}};$('addRowBtn').onclick=()=>openModal('add');$('recordForm').onsubmit=save;$('modalClose').onclick=$('modalCancel').onclick=()=>$('recordModal').classList.add('hidden');$('backButton').onclick=()=>location.href='/index.html';$('recordModal').onclick=e=>{if(e.target===$('recordModal'))$('recordModal').classList.add('hidden')};boot();
})();